----
- name: install httpd
  dnf:
    name: httpd
    state: installed

- name: start and enable httpd
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: install firewalld
  dnf:
    name: firewalld
    state: installed
 
- name: permit traffic in default zone for https service
  firewalld:
    port: "{{ http_port }}"
    permanent: yes
    state: enabled
  notify:
    - firewalld_reload
- meta: flush_handlers
