---
- name: Install php
  dnf:
    name:
      - php
      - php-mysqlnd
    update_cache: yes
    state: latest

- name: Restart Apache service
  service:
      name: httpd
      state: restarted
- name: template render
  template:
    src: page.html.j2
    dest: /var/www/html
  
